Gold standard
nexusformat/cnxvalidate pull request #28
Opened 2020-08-26 18:45 UTC by yayahjb

This is a set of companion changes for cnxvalidate to go with the gold_standard NXmx pull request for the definitions repository

2020-09-04 13:45 UTC, yayahjb commented
To all:  As discussed in the Telco, please complete your review of this pull request by 12 noon NY time on Wednesday 9 Sep 2020.

2020-09-04 18:44 UTC, PeterC-DLS requested changes

2020-09-04 18:44 UTC, PeterC-DLS commented on src/nxvfield.c
> +        fName_size=strlen(fName);
Why not use strcmp/strncmp?

2020-09-04 23:17 UTC, yayahjb commented on nxvmain.c
> +	char *defDir = strdup("/usr/local/lib/nexus_definitions");
Agreed.   Tab indentation restored with commit c7431b5

2020-09-05 00:13 UTC, yayahjb commented on nxvmain.c
> +	char *defDir = strdup("/usr/local/lib/nexus_definitions");
Certainly it would be a good ideas to make the default location of nexus_definitions a build time configuration parameter.  The exact approach should be discussed with Mark and whoever else is interested.  Since the -l option provides run-time configuration, I propose to get the rest of PR #28 merged and leave the build-time configuration suggestion for future consideration.

2020-09-05 00:15 UTC, yayahjb commented on nxvmain.c
> +      case 'd':
fixed

2020-09-05 00:24 UTC, yayahjb commented on src/nxvgroup.c
> +        xmlChar *opt= NULL;
Fixed by commit  ed2426c

2020-09-05 00:25 UTC, yayahjb commented on src/nxvfield.c
> +        fName_size=strlen(fName);
More portable, about the same amount of code.

2020-09-06 13:56 UTC, benajamin approved these changes

2020-09-06 14:17 UTC, benajamin commented on include/nxvalidate.h
>  /* NXVgetCounters retrieves the number of errors and waring found in the
I suggest fixing this comment by changing "waring" to "warnings". Best to keep things peaceful!

2020-09-06 14:27 UTC, benajamin commented on test/testbasics.cpp
> +      int status = NXVvalidate(con,"data/nofileattributes.h5", NULL, NULL, 1);
This appears to be the only test passing "1" as the last argument of NXVvalidate. If this is correct code, then I think a comment is appropriate to explain why it should be different from the surrounding code.

2020-09-06 14:30 UTC, benajamin approved these changes

2020-09-07 08:13 UTC, PeterC-DLS commented on src/nxvfield.c
> +        fName_size=strlen(fName);
ANSI C was standard last century and using a simple strcmp is 2 or 3 much more simpler lines (check for length and start of if statement).

```C
char singular_err[] ="_error";
size_t singular_err_len = strlen(singular_err); // or 7
fName_size=strlen(fName);

if (fName_size > singular_err_len && strcmp(fName + fName_size - singular_err_len, singular_err == 0) {
   ...
}
```

2020-09-07 08:18 UTC, PeterC-DLS commented on nxvmain.c
> +	char *defDir = strdup("/usr/local/lib/nexus_definitions");
As things are installed in `CMAKE_INSTALL_PREFIX` then perhaps this is a better default for now.

2020-09-07 10:40 UTC, yayahjb commented
Dear Peter,
  Personally, I am uncomfortable with your version, just as you are
uncomfortable with
mine.  Our experiences are clearly different.  Let's put the missing paren
into your code

char singular_err[] ="_error";
size_t singular_err_len = strlen(singular_err); // i.e. 7
fName_size=strlen(fName);

if (fName_size > singular_err_len

    && strcmp(fName + fName_size - singular_err_len, singular_err == 0)) {
   ...
}

and then let's leave it to the others to choose if they  want the change.
I'll go along with the consensus by Wednesday on which one is "better".
  Regards,
    Herbert

On Mon, Sep 7, 2020 at 4:14 AM Peter Chang <notifications@github.com> wrote:

> *@PeterC-DLS* commented on this pull request.
> ------------------------------
>
> In src/nxvfield.c
> <https://github.com/nexusformat/cnxvalidate/pull/28#discussion_r484265445>
> :
>
> > @@ -1056,6 +1122,22 @@ int NXVvalidateField(pNXVcontext self, hid_t fieldID,
>  	myPath = self->nxdlPath;
>  	self->nxdlPath = nxdlName;
>
> +        /* warn about use of singular _error ending a field name */
> +
> +        fName_size=strlen(fName);
>
> ANSI C was standard last century and using a simple strcmp is 2 or 3 much
> more simpler lines (check for length and start of if statement).
>
> char singular_err[] ="_error";size_t singular_err_len = strlen(singular_err); // or 7
> fName_size=strlen(fName);
> if (fName_size > singular_err_len && strcmp(fName + fName_size - singular_err_len, singular_err == 0) {
>    ...
> }
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nexusformat/cnxvalidate/pull/28#discussion_r484265445>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABB6EAM4AL2ZW3O57GEQLULSESI47ANCNFSM4QMEPKZQ>
> .
>

2020-09-09 10:46 UTC, yayahjb commented on include/nxvalidate.h
>  /* NXVgetCounters retrieves the number of errors and waring found in the
Fixed in commit  75ba9e1

2020-09-09 10:57 UTC, yayahjb commented
As of 7 am NY time on 9 Sep, operationally the changes seem to have been accepted, but we are left with 2 unresolved coding style questions from Peter Chang.  Unless I hear objections, I propose to go ahead with the cnxvalidate merge at noon, and would suggest Peter then put in new pull requests for whichever of the style changes he still feels to be appropriate.

2020-09-09 16:00 UTC, merged

2020-09-09 16:00 UTC, yayahjb commented
Merged as proposed -- Herbert